// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-0sVtXuSXppVPPHr7EvQxG0BLipcXUU0',
    appId: '1:361116656518:web:63817076bef003536dc207',
    messagingSenderId: '361116656518',
    projectId: 'dina95',
    authDomain: 'dina95.firebaseapp.com',
    storageBucket: 'dina95.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKwASmHT4WwvAaQRWJBo6vLD9_ZNbJbMw',
    appId: '1:361116656518:android:36b2678639b8b8d76dc207',
    messagingSenderId: '361116656518',
    projectId: 'dina95',
    storageBucket: 'dina95.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYnM8ROa9KHj9jGkdquH-I1pr0IXMyVDM',
    appId: '1:361116656518:ios:a38e31a666d830636dc207',
    messagingSenderId: '361116656518',
    projectId: 'dina95',
    storageBucket: 'dina95.firebasestorage.app',
    androidClientId: '361116656518-ju6g7gc6jnja0rpr2r3bmi90e9gm0fh5.apps.googleusercontent.com',
    iosClientId: '361116656518-bhol1t9munjvcfgb0pgi83php9prco71.apps.googleusercontent.com',
    iosBundleId: 'com.example.dinaflutter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYnM8ROa9KHj9jGkdquH-I1pr0IXMyVDM',
    appId: '1:361116656518:ios:a38e31a666d830636dc207',
    messagingSenderId: '361116656518',
    projectId: 'dina95',
    storageBucket: 'dina95.firebasestorage.app',
    androidClientId: '361116656518-ju6g7gc6jnja0rpr2r3bmi90e9gm0fh5.apps.googleusercontent.com',
    iosClientId: '361116656518-bhol1t9munjvcfgb0pgi83php9prco71.apps.googleusercontent.com',
    iosBundleId: 'com.example.dinaflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-0sVtXuSXppVPPHr7EvQxG0BLipcXUU0',
    appId: '1:361116656518:web:54e0a3092cc2edff6dc207',
    messagingSenderId: '361116656518',
    projectId: 'dina95',
    authDomain: 'dina95.firebaseapp.com',
    storageBucket: 'dina95.firebasestorage.app',
  );
}
